airbnb_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from rooms import views as room_view

app_name = "core"

urlpatterns = [
    path("", room_view.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path


from rooms import views as room_view

app_name = "rooms"
urlpatterns = [

    path("room/<int:pk>/detial/", room_view.RoomDetailsView.as_view(), name="room_detail"),

]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models
from users import models as user_model


# Create your models here.


class AbstractItem(core_models.TimeStampedModel):
    """
    Abstract Item model
    """
    name = models.CharField(max_length=255)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """
    Room Type model
    """

    class Meta:
        verbose_name = "Room Type"
        verbose_name_plural = "Room Types"


class Amenity(AbstractItem):
    """
    Amenity model Definition
    """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):
    """
    Facility model Definition
    """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):
    """
    House Rule model Definition
    """

    class Meta:
        verbose_name_plural = "House Rules"


class Photo(core_models.TimeStampedModel):
    """
    Photo model Definition
    """
    caption = models.CharField(max_length=255)
    file = models.ImageField(upload_to='photos/%Y/%m/%d')
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

    class Meta:
        verbose_name = "Photo"
        verbose_name_plural = "Photos"


class Room(AbstractItem):
    """
    Room model
    """
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    address = models.CharField(max_length=100)
    guest = models.PositiveIntegerField()
    beds = models.PositiveIntegerField()
    bedrooms = models.PositiveIntegerField()
    baths = models.PositiveIntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instance_booked = models.BooleanField(default=False)
    host = models.ForeignKey(user_model.User, on_delete=models.CASCADE, related_name="rooms")
    room_type = models.ForeignKey(RoomType, on_delete=models.SET_NULL, null=True, related_name="rooms")
    amenities = models.ManyToManyField(Amenity, related_name="rooms", blank=True)
    facilities = models.ManyToManyField(Facility, related_name="rooms", blank=True)
    house_rules = models.ManyToManyField(HouseRule, related_name="rooms",blank=True)

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super(Room, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('rooms:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    def total_rating(self):
        reviews = self.reviews.all()
        total = sum(review.average() for review in reviews) / len(reviews) if reviews else 0
        return round(total, 2)

rooms/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView

from rooms import models as rooms_models
from rooms.models import Room


# Create your views here.



# def all_rooms(request):
#     page_num = request.GET.get('page', 1)
#     page = int(page_num)
#     room_list = Room.objects.all()
#     paginator = Paginator(room_list, 10, orphans=5)
#     rooms = paginator.page(page)
#     context = {'page': rooms, }
#     return render(request, 'rooms/room_list.html', context)


class HomeView(ListView):
    """
    HomeView
    """
    model = rooms_models.Room
    paginate_by = 10
    paginate_orphans = 5
    context_object_name = 'rooms'



# def room_details(request, pk):
#     room = get_object_or_404(rooms_models.Room, pk=pk)
#     amenities = room.amenities.all()
#     context = {
#         'room': room,
#         'amenities': amenities,
#     }
#     return  render(request, 'rooms/room_detail.html', context)


class RoomDetailsView(DetailView):
    """
    Room DetailsView
    the template name is room_detail.html
    """
    model = rooms_models.Room

templates/rooms/room_detail.html
{% extends 'base.html' %}

{% load static %}

{% block page_name %}
home
{% endblock page_name %}

{% block content %}

<div class="row">
    <div>
        <h1>{{room.name}}</h1>
        <hr/>
        <h4>{{room.description}}</h4>
    </div>

    <div>
        <h2> By: {{room.host}} </h2>
        <h5>Amenities display</h5>
        <ul>
            {% for amenity in room.amenities.all %}
        <li>{{amenity.name}}</li>
        {% endfor %}
        </ul>
        <h5>Facilities</h5>
           <ul>
            {% for facility in room.facilities.all %}
        <li>{{facility.name}}</li>
        {% endfor %}
        </ul>
         <h5>House rules</h5>
           <ul>
            {% for rules in room.house_rules.all %}
        <li>{{rules.name}}</li>
        {% endfor %}
        </ul>
    </div>

    <div>

    </div>
</div>

{% endblock content %}

templates/rooms/room_details.html
{% extends 'base.html' %}

{% load static %}

{% block page_name %}
home
{% endblock page_name %}

{% block content %}

<div class="row">
    <div>
        <h1>{{room.name}}</h1>
        <hr/>
        <h4>{{room.description}}</h4>
    </div>

    <div>
        <h2> By: {{room.host}} </h2>
        <h5>Amenities display</h5>
        <ul>
            {% for amenity in amenities %}
        <li>{{amenity.name}}</li>
        {% endfor %}
        </ul>
        <h5>Facilities</h5>
           <ul>
            {% for facility in room.facilities.all %}
        <li>{{facility.name}}</li>
        {% endfor %}
        </ul>
         <h5>House rules</h5>
           <ul>
            {% for rules in room.house_rules.all %}
        <li>{{rules.name}}</li>
        {% endfor %}
        </ul>
    </div>

    <div>

    </div>
</div>

{% endblock content %}

templates/rooms/room_list.html
{% extends 'base.html' %}

{% load static %}

{% block page_name %}
home
{% endblock page_name %}

{% block content %}

{% for room in rooms %}
<h4>
    <a href="{% url 'rooms:room_detail' room.pk %}">{{ room.name }}</a>
</h4>
{% endfor %}

<h5>
    {% if page_obj.has_previous %}
    <a href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}


    Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}


    {% if page_obj.has_next %}
    <a href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}
</h5>


{% endblock content %}